### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by ipa-rwu**

### CODE REVIEW

**Review by ipa-kut — APPROVED** [review]

**Review by ipa-kut — CHANGES_REQUESTED** [review]
Looks like the CI jobs are failing, these failing elements should either be fixed or bypassed.

**Comment by ipa-rwu** [comment]
This is not ci setup probleam. It is because of our tests.

**Comment by ipa-kut** [comment]
> 
> 
> This is not ci setup probleam. It is because of our tests.

Yes I know, please fix these tests if you have the time, otherwise comment out their registration in the CMakeLists.txt of their respective packages with a comment like TODO:Fix + make an issue in the repo so that either us or a student can later fix them.

**Comment by ipa-rwu** [comment]
@ipa-kut Please check and merge it

**Review by ipa-kut — APPROVED** [review]

**Pull request merged**
